#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use App\Domain\JobFactory;
use App\Framework\Console\JobConsoleCommand;
use App\ConfigurationCompiler;
use App\ConfigurationProcessor;
use Symfony\Component\Console\Application;
use Symfony\Component\Finder\Finder;

$processor = new ConfigurationProcessor();
$compiler = new ConfigurationCompiler();

$configuration = $processor->process([
    __DIR__ . "/reel.yml"
]);

$properties = $compiler->compile($configuration["properties"]);

$app = new Application("reel", file_get_contents('/VERSION'));
$app->add(new \App\Framework\Console\PropertiesConsoleCommand());

loadReelPipelines($app);
loadCustomPipelines($app);

$app->run();

/**
 * @param Application $app
 * @return void
 */
function loadReelPipelines(Application $app): void
{
    loadPipelines($app, __DIR__ . "/pipelines");
}

/**
 * @param Application $app
 * @return void
 */
function loadCustomPipelines(Application $app): void
{
    loadPipelines($app, getcwd() . "/.reel/pipelines", "app");
}

/**
 * @param Application $app
 * @param string $directory
 * @param string $prefix
 * @return void
 */
function loadPipelines(Application $app, string $directory, string $prefix = ""): void
{
    $finder = new Finder();
    $pipelineFactory = new JobFactory($finder);
    $pipelineDirectory = realpath($directory);

    if ($pipelineDirectory) {
        foreach ($pipelineFactory->createPipelines($pipelineDirectory, $prefix) as $pipeline) {
            $app->add(new JobConsoleCommand($pipeline));
        }
    }
}
