#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use App\Framework\Console\JobConsoleCommand;
use Symfony\Component\Console\Application;

$config = new \App\Domain\Config();
$config->addDirectory(new \App\Domain\ConfigDirectory(__DIR__ . "/.reel", ""));
$config->addDirectory(new \App\Domain\ConfigDirectory(getcwd() . "/.reel", "app"));

$finderFactory = new \App\Domain\Glue\FinderFactory();
$yamlParserFactory = new \App\Domain\Glue\YamlParserFactory();
$jobFactory = new \App\Domain\JobFactory();

$reel = (new \App\Domain\ReelFactory($finderFactory, $yamlParserFactory, $jobFactory))->create($config);

$app = new Application("reel", file_get_contents('/VERSION'));

foreach ($reel->getJobs() as $job) {
    $app->add(new JobConsoleCommand($job));
}

$app->run();
